import Navbar from '@/components/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import LogoIcon from '../public/logo.svg';
const inter = Inter({ subsets: ['latin'] });
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Quiz Maker',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: LogoIcon.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme='enterwell'>
      <body className={`${inter.className} relative flex flex-col pb-10`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
